version: 0.2

phases:
  install:
    commands:      
      - echo Installing source NPM
      - cd packages/auth && npm install
  pre_build:
    commands:
      - echo Installing dependencies...     
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - aws s3 sync packages/auth/dist s3://auth-dev-test --acl 'public-read' --delete
